export const WORDS = [
  "APPLE","ABOUT","ABOVE","ALERT","ALLOW","ALIVE","ALONE","AMONG","ANGLE","ANGER",
  "APART","ARGUE","ARISE","AUDIO","AWARE","BADLY","BASIC","BEACH","BEAUT","BEGIN",
  "BEING","BELOW","BENCH","BIRTH","BLACK","BLAME","BLEND","BLIND","BLOCK","BLOOD",
  "BOARD","BOUND","BRAIN","BRAND","BRAVE","BREAK","BRIEF","BRING","BROAD","BROWN",
  "BUILD","BURST","CABLE","CALM","CARRY","CATCH","CAUSE","CHAIN","CHAIR","CHALK",
  "CHAMP","CHART","CHASE","CHEAP","CHECK","CHEEK","CHEST","CHIEF","CHILD","CHINA",
  "CHOSE","CIVIL","CLAIM","CLASS","CLEAN","CLEAR","CLERK","CLICK","CLIMB","CLOCK",
  "CLOSE","COAST","COLOR","COULD","COUNT","COURT","COVER","CRAFT","CRASH","CRIME",
  "CROWD","CROWN","CRUEL","CURVE","CYCLE","DANCE","DEATH","DEBUT","DEPTH","DOING",
  "DOUBT","DOZEN","DRAFT","DRAMA","DRAWN","DREAM","DRESS","DRINK","DRIVE","EARLY",
  "EARTH","EIGHT","ELDER","EMPTY","ENJOY","ENTER","ENTRY","EQUAL","ERROR","EVENT",
  "EVERY","EXACT","EXIST","EXTRA","FAITH","FALSE","FAULT","FIELD","FIFTH","FIFTY",
  "FINAL","FIRST","FIXED","FLAME","FLASH","FLOOR","FOCUS","FORCE","FORGE","FOUND",
  "FRAME","FRESH","FRONT","FRUIT","FUNNY","GIANT","GIVEN","GLASS","GLOBE","GOING",
  "GRACE","GRADE","GRAND","GRANT","GRASS","GREAT","GREEN","GROUP","GUARD","GUESS",
  "GUIDE","HABIT","HAPPY","HEARD","HEART","HEAVY","HONEY","HORSE","HOTEL","HOUSE",
  "HUMAN","HUMOR","HUNGR","IDEAL","IMAGE","IMPLY","INDEX","INNER","INPUT","ISSUE",
  "JEANS","JEWEL","JOINT","JUDGE","JUICE","KNOWN","LABEL","LABOR","LARGE","LASER",
  "LAUGH","LEARN","LEAST","LEAVE","LEGAL","LEVEL","LIGHT","LIMIT","LOCAL","LOGIC",
  "LOOSE","LUCKY","LUNCH","MAGIC","MAJOR","MAKER","MAPLE","MARCH","MATCH","MAYBE",
  "MEANT","MEDAL","MEETING","METAL","MIGHT","MINOR","MIXED","MODEL","MONEY","MONTH",
  "MORAL","MORSE","MOTOR","MOUNT","MOUSE","MOVIE","MUSIC","NAKED","NEEDS","NERDY",
  "NEVER","NIGHT","NOISE","NORTH","NOTED","NOVEL","NURSE","OBJECT","OCCUR","OFFER",
  "OFTEN","OLDER","ORDER","OTHER","OUTER","OWNED","OWNER","PAINT","PANEL","PANIC",
  "PARTY","PEACE","PHASE","PHONE","PHOTO","PIECE","PILOT","PLACE","PLAIN","PLANT",
  "PLATE","POINT","POWER","PRESS","PRICE","PRIDE","PRINT","PRIZE","PROOF","PROUD",
  "PROVE","PUBLIC","PULLS","QUICK","QUIET","RADIO","RAISE","RANGE","RAPID","RATIO",
  "READY","REACH","REACT","REPLY","RIGHT","RIVER","ROBOT","ROUGH","ROUND","ROYAL",
  "RURAL","SCALE","SCENE","SCOPE","SCORE","SCOUT","SCREW","SHARE","SHARP","SHEEP",
  "SHEET","SHELF","SHELL","SHIFT","SHINE","SHIRT","SHOCK","SHOOT","SHORT","SHOUT",
  "SHOWN","SIGHT","SIMIL","SIMPLE","SINCE","SKILL","SKIRT","SLEEP","SMALL","SMART",
  "SMILE","SMOKE","SOLAR","SOLID","SORRY","SOUND","SPACE","SPARE","SPEAK","SPEED",
  "SPEND","SPENT","SPICE","SPINE","SPORT","STAGE","STAKE","STAND","START","STATE",
  "STEAM","STEEL","STICK","STILL","STOCK","STORM","STORY","STRIP","STRONG","STUDY",
  "STUFF","STYLE","SUGAR","SUPER","SWEET","TABLE","TAKEN","TASTE","TEACH","TEAMS",
  "TEARS","THEIR","THEME","THICK","THING","THINK","THIRD","THOSE","THREE","THROW",
  "TIGHT","TIMES","TIRED","TITLE","TODAY","TOOTH","TOPIC","TOTAL","TOUCH","TOWER",
  "TRACK","TRADE","TRAIN","TREAT","TREND","TRIAL","TRUCK","TRULY","TRUST","TRUTH",
  "TWICE","UNDER","UNION","UNITE","UNTIL","UPPER","URBAN","USUAL","VALUE","VIDEO",
  "VISIT","VOICE","WASTE","WATCH","WATER","WEIGH","WHERE","WHILE","WHITE","WHOLE",
  "WOMAN","WORRY","WORSE","WORTH","WOULD","WRITE","WRONG","YOUNG","YOUTH"
];

export const pickTarget = () => {
  return WORDS[Math.floor(Math.random() * WORDS.length)];
};

export const isAllowedWord = (w: string) => {
  if (w.length !== 5) return false;
  return /^[a-zA-Z]{5}$/.test(w);
};

export const evaluateGuess = (guess: string, target: string) => {
  const result: ("correct" | "present" | "absent")[] = [];
  const t = target.split("");

  guess.split("").forEach((ch, i) => {
    if (ch === target[i]) result.push("correct");
    else if (t.includes(ch)) result.push("present");
    else result.push("absent");
  });

  return result;
};